apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: ebs-volume
spec:
  storageClassName: ""
  capacity:
    storage: "2Gi" 
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore: 
    fsType: ext4
    volumeID: vol-0d46a9c0bb23f7fce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-volume
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: "var/log/nginx/html"  
      volumes:
        - name: nginx-html
          persistantVolumeClaim:
            claimName: ebs-volume
