apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "ebs-volume" 
spec:
  capacity:
    storage: "1Gi" 
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore: 
    fsType: ext4
    volumeID: vol-0d46a9c0bb23f7fce